### ISSUE TITLE
Event example does not work

### ISSUE THREAD

**Issue by ranok** [karaxnim/karax#241] opened 2023-02-26 03:09 UTC
Using the button.nim example from the README results in the same uncaught AssertionDefect as #86 and #123. 

Below is an image of the DevTools console output when I click the button (I renamed the file to albiero, but otherwise it's a direct copy/paste from the examples.:
![image](https://user-images.githubusercontent.com/66790/221390106-9342e412-c7b3-4609-a678-ca718c49c89d.png)

This is with karax 1.2.2 and nim 1.6.10.

**Comment by geotre** [comment] 2023-02-26 16:53
Recently fixed an issue (#232) where a browser extension was modifying the dom, seems like this could be similar. Once we can replicate the cause it should be possible to fix.

@ranok can you confirm which browser you are seeing this in, and with which extensions? If you have a lot of extensions installed, maybe try disabling some too see if you can figure out which is causing it.

You can also check the dom inspector in devtools to see if anything looks off (and post a screenshot here if so)

**Comment by ranok** [comment] 2023-02-26 17:37
I'll try it in safemode and slowly add them back in shortly

**Comment by ranok** [comment] 2023-02-26 19:18
Good catch, Adblock for Youtube oddly gets permissions for all sites and was somehow causing issues, by restricting it to only Youtube the example works again.

**Comment by geotre** [comment] 2023-02-27 10:20
Thank you for confirming @ranok. I imagine the extension requests all pages so that it can also block ads on embedded youtube videos.

I would still like to fix this as it may impact other users. I can't replicate it by installing the extension, can you share what change it made to the browser dom?

**Comment by ranok** [comment] 2023-02-27 15:11
Here are the two `div`s the [extension](https://chrome.google.com/webstore/detail/adblock-for-youtube/cmedhionkhpnakcndndgjdbohmhepckk?hl=en) injects: 
![image](https://user-images.githubusercontent.com/66790/221599811-128a271e-f844-4c58-93a2-05591ab98dd4.png)

If I make another `div` preceding the ROOT one that Karax uses, the extension injects into that one, and Karax works as expected:

```
<!doctype html>
<html>
    <head>
        <title>Testing</title>
    </head>
    <body id="body">
        <div id="preroot"></div><!-- the extension injects into this div now -->
        <div id="ROOT"></div>
        <script src="karax.js" type="text/javascript"></script>
    </body>
</html>
```

**Comment by Araq** [comment] 2023-03-01 13:55
>  Perhaps they could be opt in with a -d:karaxCheckSame flag or similar when needed for debugging? What do you think @Araq?

Sounds good to me. At least I cannot think of a better solution.

**Comment by geotre** [comment] 2023-03-02 23:10
#244 has been merged, which should solve this issue. @ranok if you have a chance to check with your browser extension re-enabled please let us know if the issue persists.

I will close the issue again in the meantime.

**Closed by geotre** 2023-03-02 23:10 UTC
