### ISSUE TITLE
input.value ignored when rendering on non-js target

### ISSUE THREAD

**Issue by dawkot** [karaxnim/karax#126] opened 2019-10-31 20:36 UTC
### Example

```nim
import karax / [vdom, karaxdsl]

echo build_html input(class="foo", value="bar")
```

### Output

`<input class="foo"></input>`

### Expected Output

`<input class="foo" value="bar"></input>`

**Comment by zedeus** [comment] 2019-11-11 20:06
Duplicate of #61

**Comment by dawkot** [comment] 2019-11-23 15:51
> Duplicate of #61

I thought that one was just about `value` not being reactive

**Comment by ajusa** [comment] 2021-05-02 21:00
Closing as it is a duplicate. https://github.com/karaxnim/karax/issues/61#issuecomment-520909139 is the specific comment where the server side rendering was brought up.

**Closed by ajusa** 2021-05-02 21:00 UTC
