### ISSUE TITLE
Can't Render SVG

### ISSUE THREAD

**Issue by sdmcallister** [karaxnim/karax#170] opened 2021-01-12 12:06 UTC
I've tried without success:

```
proc createDom(): VNode =
  result = buildHtml(tdiv):
    svg(width = "100", height="100"):
      circle(cx="50", cy="50", r="40", stroke="green", stroke-width="4", fill="yellow")
      text "Doesn't Support SVG"
```
Everything compiles fine with no errors amd I can see the Element in the Browser developer mode, but the image doesn't render and I see the text. On on the latest version of Chrome.

**Comment by sdmcallister** [comment] 2021-01-20 11:17
This seems to work:
```
tdiv:
  verbatim """<svg width=100 height=100>
                        <circle cx=50 cy=50 r=40 stroke=green stroke-width=4 fill=yellow />
                      </svg>"""
```

**Comment by planetis-m** [comment] 2021-02-04 19:51
Same with firefox

**Comment by planetis-m** [comment] 2021-02-04 20:07
So the problem is empty tags, browser prefer self closing tags in that case.

**Comment by tandy-1000** [comment] 2021-08-06 19:18
I have found this issue to also affect rendering gifs.

**Comment by geotre** [comment] 2023-10-20 15:39
SVG support added in #271

**Closed by geotre** 2023-10-20 15:39 UTC
Labels: bug
