### ISSUE TITLE
Can we have a static version of kxi?

### ISSUE THREAD

**Issue by gogolxdong** [karaxnim/karax#93] opened 2019-04-23 09:32 UTC
Karax is designed for Web APP, though it has some basice support for static website. I was wondering whether we have a chance to have something like
```nim
proc `$`(k: karaxInstance): kstring
```
so that the static webiste generating from Karax become seamless.

**Comment by kidandcat** [comment] 2019-05-14 07:12
this looks like a duplicate of #90

**Comment by ajusa** [comment] 2021-05-02 21:39
Yeah, I think this can be closed with https://github.com/karaxnim/karax/pull/162 now.

**Closed by ajusa** 2021-05-02 21:39 UTC
